### ISSUE TITLE
'outputs_QGISEXTRACTBYLOCATION_1' is not defined

### ISSUE THREAD

**Issue by cbertelli** [pjgeng/Contour-Labels#1]
The error says:
name 'outputs_QGISEXTRACTBYLOCATION_1' is not defined See log for more details
The log does not suggest anything else.
The version of QGIS is 2.18.5 (built with brew on MacOS 10.9.5).
Sorry for bothering, can you provide any cue to solve the issue?

**Comment by pjgeng** [comment]
If you look at the code for the processing script lines 170-179 there are version specific items for the two versions mentioned in the readme. Currently the script supports 2.14.8 LTE or 2.16.1 only.
I am working on updating the script to support 2.18.4 as that's the version I'm using for now. 
As 2.14.15 is now the LTR there will be an update shortly to support that.
